

CREATE TABLE `list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL DEFAULT '',
  `content` TEXT NOT NULL DEFAULT '',
  `ctime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'create time',
  `mtime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'modify time',
  `belong` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `deleted` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `belong_inx` (`belong`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;